### ISSUE TITLE
storageClass is not respected

### ISSUE THREAD

**Issue by KamalAman** [riskfocus/helm-charts-public#26]
I am trying to change the storageClass for persistant volumes for both the Job Manager and Task Manager

```
flink:
  image.repository: flink
  workers: 1
  taskmanager:
    replicaCount: 3
    persistent:
      enabled: true
      storageClass: <storageClassName>
      size: 7Gi
  jobmanager:
    persistent:
      enabled: true
      storageClass: <storageClassName>
```

However, no matter what I do, the default storage class is always used.
