### ISSUE TITLE
Flink ingress

### ISSUE THREAD

**Issue by andrelsyoo** [riskfocus/helm-charts-public#38]
Hello Team, 

I'm unable to create Flink ingress through its chart! so far I've tried several ways to do it by following the template pattern of ingress.yaml but no success.

Please there is away to provide a sample of the required configuration in order to get it properly created? so far tried as follow:

```
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: [develop.mydomain.com]
  tls: [tls-ingress]
```

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: develop.mydomain.com
  tls: tls-ingress
```

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: "develop.mydomain.com"
  tls: tls-ingress
```

```
ingress:                       
  enabled: true                
  annotations: {}              
  path: /                      
  hosts:                       
  tls:                         
    - hosts:                   
      -develop.mydomain.com
      secretName: tls-ingress
  rules:                       
    - host: develop.mydomain.com
      http:                    
        paths:                 
          - backend:           
              service:         
                name: flink-job
                port:          
                  number: 8081 
            path: /            
            pathType: Prefix   
```
